export const albums = [
  {
    title: "Taylor Swift",
    stolenCover: "../src/assets/img/cover-taylor-swift.jpg",
    cover: "../src/assets/img/cover-taylor-swift.jpg",
    wasStolen: true,
    hasTV: false,
    fromTheVault: [],
  },
  {
    title: "Fearless",
    stolenCover: "../src/assets/img/cover-fearless.jpg",
    cover: "../src/assets/img/cover-fearless-tv.png",
    wasStolen: true,
    hasTV: true,
    fromTheVault: [
      { title: "You All Over Me (feat. Maren Morris" },
      { title: "Mr. Perfectly Fine" },
      { title: "We Were Happy" },
      { title: "That's When (feat. Keith Urban)" },
      { title: "Don't You" },
      { title: "Bye Bye Baby" },
    ],
  },
  {
    title: "Speak Now",
    stolenCover: "../src/assets/img/cover-speak-now.webp",
    cover: "../src/assets/img/cover-speak-now-tv.webp",
    wasStolen: true,
    isTV: true,
    fromTheVault: [
      { title: "Electric Touch (feat. Fall Out Boy" },
      { title: "When Emma Falls in Love" },
      { title: "I Can See You" },
      { title: "Castles Crumbling (feat. Hayley Williams)" },
      { title: "Foolish One" },
      { title: "Timeless" },
    ],
  },
  {
    title: "Red",
    stolenCover: "../src/assets/img/cover-red.jpg",
    cover: "../src/assets/img/cover-red-tv.jpg",
    wasStolen: true,
    isTV: true,
    fromTheVault: [
      { title: "State of Grace (acoustic version)" },
      { title: "Ronan" },
      { title: "Better Man" },
      { title: "Nothing New (feat. Phoebe Bridgers)" },
      { title: "Babe" },
      { title: "Message in a Bottle" },
      { title: "I Bet You Think About Me (featuring Chris Stapleton)" },
      { title: "Forever Wintere" },
      { title: "Run (featuring Ed Sheeran)" },
      { title: "The Very First Night" },
      { title: "All Too Well (10 Minute Version)" },
    ],
  },
  {
    title: "1989",
    stolenCover: "../src/assets/img/cover-1989.webp",
    cover: "../src/assets/img/cover-1989.webp",
    wasStolen: true,
    isTV: false,
    fromTheVault: [],
  },
  {
    title: "Reputation",
    stolenCover: "../src/assets/img/cover-reputation.jpg",
    cover: "../src/assets/img/cover-reputation.jpg",
    wasStolen: true,
    isTV: false,
    fromTheVault: [],
  },
  {
    title: "Lover",
    stolenCover: "../src/assets/img/cover-lover.jpg",
    cover: "../src/assets/img/cover-lover.jpg",
    wasStolen: false,
    isTV: true,
    fromTheVault: [],
  },
  {
    title: "Folklore",
    stolenCover: "../src/assets/img/cover-folklore.jpg",
    cover: "../src/assets/img/cover-folklore.jpg",
    wasStolen: false,
    isTV: true,
    fromTheVault: [],
  },
  {
    title: "Evermore",
    stolenCover: "../src/assets/img/cover-evermore.jpg",
    cover: "../src/assets/img/cover-evermore.jpg",
    wasStolen: false,
    isTV: true,
    fromTheVault: [],
  },
  {
    title: "Midnights",
    stolenCover: "../src/assets/img/cover-midnights.png",
    cover: "../src/assets/img/cover-midnights.png",
    wasStolen: false,
    isTV: true,
    fromTheVault: [],
  },
];
